/** Shared content for the Word/PDF report and the Excel workbook. */

const defects = [
  { id: 'DEF-01', severity: 'High', area: 'Security', title: "Any logged-in user can edit another user's profile",
    detail: "PUT /api/users/{id} updates whichever id is in the URL; there is no check that it belongs to the caller. Debater A changed Debater B's bio (the profile-picture upload endpoint follows the same pattern).",
    foundBy: 'JUnit OwnershipSecurity · Postman 06', fix: 'Compare the id with the authenticated user (or allow organizers only) before updating.' },
  { id: 'DEF-02', severity: 'High', area: 'Security', title: 'Discussion comments can be posted under someone else\'s name',
    detail: 'POST /api/discussion takes the author from the "userId" field in the request body instead of the login token.',
    foundBy: 'JUnit OwnershipSecurity · Postman 06', fix: 'Ignore userId in the body; use the authenticated user.' },
  { id: 'DEF-03', severity: 'High', area: 'Functional', title: "Judge's score sheet ignores the organizer's custom criteria",
    detail: 'GET /api/score-templates/{id} fails with "Type definition error ... ByteBuddyInterceptor" (a raw JPA entity with a lazy proxy is returned). The page swallows the error and silently falls back to built-in criteria.',
    foundBy: 'JUnit Workflow · Postman 04 · Playwright 05', fix: 'Return a DTO (id, name, criteriaJson) instead of the entity.' },
  { id: 'DEF-04', severity: 'Medium', area: 'Functional', title: '"Already submitted" check on the score sheet never works',
    detail: 'GET /api/score-sheets/{match}/{judge} fails with the same serialization error, so a judge who already submitted sees an empty form again; re-submitting is then rejected by the server.',
    foundBy: 'JUnit Workflow · Postman 04 · Playwright 05', fix: 'Return a DTO for ScoreSheetSubmission.' },
  { id: 'DEF-05', severity: 'Medium', area: 'Security / UX', title: 'Expired or invalid login returns 403 instead of 401, so users are never logged out',
    detail: 'Spring Security has no authentication entry point configured, so missing/expired tokens get 403. The frontend only logs out on 401, so an expired session leaves the user on a page where every request fails.',
    foundBy: 'JUnit RBAC · Postman 03 · Playwright 02', fix: 'Add .exceptionHandling(e -> e.authenticationEntryPoint(new HttpStatusEntryPoint(HttpStatus.UNAUTHORIZED))).' },
  { id: 'DEF-06', severity: 'Medium', area: 'Security', title: "An organizer can delete another organizer's tournament",
    detail: 'DELETE /api/tournaments/{id} checks the ORGANIZER role but not ownership.',
    foundBy: 'JUnit OwnershipSecurity', fix: 'Allow delete only when tournament.organizer is the caller.' },
  { id: 'DEF-07', severity: 'Medium', area: 'Security', title: "Any logged-in user can delete anyone's discussion comment",
    detail: 'DELETE /api/discussion/{id} has no ownership check.',
    foundBy: 'JUnit OwnershipSecurity · Postman 06', fix: 'Allow only the author (or the tournament organizer).' },
  { id: 'DEF-08', severity: 'Medium', area: 'Privacy', title: 'Public user list exposes every e-mail address',
    detail: 'GET /api/users is public and returns each user\'s e-mail to anonymous visitors.',
    foundBy: 'JUnit OwnershipSecurity · Postman 06', fix: 'Use a public profile DTO without e-mail, or require login.' },
  { id: 'DEF-09', severity: 'Low', area: 'Security', title: "Users can mark other users' notifications as read",
    detail: 'PUT /api/notifications/{id}/read receives the username but never checks it.',
    foundBy: 'JUnit OwnershipSecurity · Postman 06', fix: 'Check notification.user == caller.' },
  { id: 'DEF-10', severity: 'Low', area: 'API', title: 'Role-denied requests return 400 instead of 403',
    detail: 'GlobalExceptionHandler catches RuntimeException, which includes Spring\'s AccessDeniedException, and turns "Access Denied" into 400. Access is still correctly blocked.',
    foundBy: 'JUnit RBAC · Postman 03/04', fix: 'Add an @ExceptionHandler(AccessDeniedException.class) returning 403.' },
  { id: 'DEF-11', severity: 'Low', area: 'Functional', title: 'Home page always shows 0 live matches to visitors',
    detail: 'The public home page calls GET /api/matches/live, which is not in the public list in SecurityConfig, so visitors get 403 (also logged as a console error by Lighthouse).',
    foundBy: 'JUnit RBAC · Postman 01 · Playwright 04 · Lighthouse', fix: 'Permit GET /api/matches/** for everyone.' },
  { id: 'DEF-12', severity: 'Low', area: 'API', title: '/api/auth/me without a token returns 400 (server error) instead of 401',
    detail: '/api/auth/** is fully public, so the controller runs with no Authentication and throws a NullPointerException.',
    foundBy: 'JUnit RBAC · Postman 02', fix: 'Permit only /api/auth/login and /signup; require auth for /me.' },
  { id: 'DEF-13', severity: 'Low', area: 'Validation', title: 'Sign-up accepts invalid e-mail addresses',
    detail: 'SignupRequest has no validation annotations, so "not-an-email" is stored.',
    foundBy: 'JUnit Auth · Postman 02', fix: 'Add @Valid with @Email/@NotBlank/@Size on SignupRequest.' },
  { id: 'DEF-14', severity: 'Low', area: 'UI', title: 'Session warning modal text is hard to read',
    detail: 'SessionChangedModal still uses the old dark-theme classes (glass-dark, text-white), so after the UI refresh the title and message are white on a light panel.',
    foundBy: 'Playwright screenshot review', fix: 'Restyle the modal with the new theme colors.' },
  { id: 'DEF-15', severity: 'Low', area: 'Accessibility', title: 'Login page accessibility issues',
    detail: 'The show/hide password button has no accessible name; some text fails color-contrast; pages have no <main> landmark or meta description.',
    foundBy: 'Lighthouse', fix: 'Add aria-label to icon buttons, a <main> element and a meta description.' },
];

const observations = [
  'The default JWT secret and a database password are committed in application.properties. Anyone who reads the repository could forge login tokens if production ever runs with the default secret. Set JWT_SECRET and DB_PASSWORD only as environment variables.',
  'The home page lists the first 6 tournaments (oldest first), so new tournaments disappear from it as the list grows.',
  'Generating the next knockout round silently drops a winner when there is an odd number of winners.',
  'The one existing frontend test (LoginPage.test.tsx) had been broken since the UI redesign changed the password placeholder. It was rewritten as part of this work.',
];

const history = [
  ['c045431', '2026-09-21', 'Pathi-02', 'Multiple log-ins in one browser conflicted', 'Regression-tested: AuthContext.test.tsx and Playwright 02 (passing)'],
  ['c0a3d93', '2026-09-21', 'Pathi-02', 'No warning when session ended in another tab', 'Regression-tested: AuthContext.test.tsx and Playwright 02 (passing)'],
  ['eebd145', '2026-09-22', 'Pathi-02', 'Notification bugs', 'Notification flow covered by JUnit Workflow and Postman 04/05'],
  ['dec7edb', '2026-07-10', 'Jeyanth3', 'Tournament creation issue', 'Wizard covered by Playwright 03 (passing)'],
  ['b1a77ed', '2026-07-09', 'Jeyanth3', 'Submit button issue', 'Score submission covered by Playwright 03 (passing)'],
  ['9d3ff79', '2026-07-09', 'Jeyanth3', 'Profile issue', 'Profile update covered by JUnit OwnershipSecurity'],
  ['e7c7f7e', '2026-05-02', 'Jeyanth3', 'Organizer and judge dashboard issue', 'Dashboard access covered by App.test.tsx and Playwright 01'],
  ['980dcf4', '2026-05-02', 'Jeyanth3', 'Viewer-side dashboard and notification access', 'Covered by App.test.tsx route rules'],
  ['87645b6', '2026-05-02', 'Jeyanth3', 'Debater search menu UI bug', 'Debater search used in Playwright 03 wizard (passing)'],
  ['c655b0d', '2026-05-01', 'Jeyanth3', 'Login issue', 'Covered by LoginPage.test.tsx and Playwright 01 (passing)'],
  ['e18de01', '2026-06-13', 'Jeyanth3', 'TypeScript build errors for Vercel', 'Build check: vite build succeeds'],
];

const tools = [
  ['JUnit 5', 'Backend unit & integration test framework', 'Standard for Spring Boot; already included via spring-boot-starter-test'],
  ['Mockito', 'Replaces repositories with fakes in unit tests', 'Tests business rules in isolation, in milliseconds'],
  ['Spring MockMvc + spring-security-test', 'Calls real controllers through the real security filter chain', 'Verifies RBAC and HTTP status codes without starting a server'],
  ['H2 (PostgreSQL mode)', 'In-memory database for integration tests', 'Fast, repeatable, never touches real data'],
  ['JaCoCo', 'Backend code-coverage report', 'Shows which lines and branches the tests exercised'],
  ['Vitest + React Testing Library', 'Frontend component & logic tests', 'Native to Vite; tests the UI the way a user sees it'],
  ['@vitest/coverage-v8', 'Frontend coverage report', 'Built into the Vitest toolchain'],
  ['Postman + Newman', 'API end-to-end scenario, run from the command line', 'The collection can be opened in Postman for a live demo; Newman produces HTML/JUnit reports'],
  ['Playwright (Microsoft Edge)', 'Browser end-to-end tests with screenshots and traces', 'Drives the real UI against the real backend and database'],
  ['Google Lighthouse', 'Performance, accessibility, best-practice and SEO audit', 'Industry-standard non-functional quality scores'],
  ['GitHub Actions', 'Runs the suites automatically on every push', 'Keeps tests running after the presentation'],
];

module.exports = { defects, observations, history, tools };
